version: '3.8'

services:
  ratings-data-service:
    build: ./ratings-data-service
    depends_on:
      - discovery-service
    ports:
      - "8083:8083"
    networks:
      - ms-network
    restart: always
    environment:
      server.port: 8083
      eureka.client.service-url.defaultZone: http://discovery-service:8761/eureka

  movie-info-service:
    build: ./movie-info-service
    depends_on:
      - discovery-service
    ports:
      - "8082:8082"
    networks:
      - ms-network
    restart: always
    environment:
      server.port: 8082
      eureka.client.service-url.defaultZone: http://discovery-service:8761/eureka


  movie-catalog-service:
    build: ./movie-catalog-service
    depends_on:
      - discovery-service
      - movie-info-service
      - ratings-data-service
    ports:
      - "8085:8085"
    networks:
      - ms-network
    restart: always
    environment:
      server.port: 8085
      eureka.client.service-url.defaultZone: http://discovery-service:8761/eureka


  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    networks:
      - ms-network
    restart: always
    environment:
      eureka.instance.hostname: discovery-service
      eureka.client.service-url.defaultZone: http://discovery-service:8761/eureka

networks:
  ms-network:
    driver: bridge


